name = "TrueAndErrorDependentModels"
uuid = "07e9ded4-b20f-4255-9023-380d1af610f1"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
